[workspace]
resolver = "2"
members = ["crates/process", "crates/usercopy", "crates/vfs"]

[workspace.package]
edition = "2024"
rust-version = "1.85"
authors = [
    "朝倉水希 <asakuramizu111@gmail.com>",
    "Mivik <mivikq@gmail.com>",
    "陈天意 <hi@tychen.cc>",
]
license = "Apache-2.0"
repository = "https://github.com/chenty2333/thekernel-linux-abi"
homepage = "https://github.com/chenty2333/thekernel-linux-abi"

[workspace.dependencies]
bytemuck = { version = "1.24", default-features = false }
intrusive-collections = "0.9"
kspin = "0.1"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[workspace.lints.clippy]
undocumented_unsafe_blocks = "deny"
